### ISSUE TITLE
Error in running visualization validation

### ISSUE THREAD

**Issue by GalAvineri** [sunset1995/pytorch-layoutnet#10]
I've done the following steps:  
1. Built the directory tree as you instructed  
2. ran python torch2pytorch_data.py annd python torch2pytorch_pretrained_weight.py with their instructed parameters  
But when i run 'python visual.py --flip --rotate 0.25 0.5 0.75 --img_glob "data/test/img/pano_aaccxxpwmsdgvj.png" --line_glob "data/test/line/pano_aaccxxpwmsdgvj.png" --output_dir assert/'  
I get the following error 

Traceback (most recent call last):
  File ".../LayoutNet/visual.py", line 55, in <module>
    encoder.load_state_dict(torch.load('%s_encoder.pth' % args.path_prefix))
  File ".../lib/python3.5/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'ckpt/pre_encoder.pth'

**Comment by sunset1995** [comment]
Sorry for the late reply.
What is the arguments you given to the `torch2pytorch_pretrained_weight.py`?
The script should convert to pretrained model to the path you given to the `--encoder`...

**Comment by GalAvineri** [comment]
I was able to solve this eventually.
The script says it is looking for 'ckpt/pre_encoder.pth' but I had 'ckpt/pre_full_encoder.pth' instead.
So I changed the prefix parameter and than it worked.

Due to the fact that following your instructions result in a 'pre_full_encoder.pth' file instead of a 'pre_encoder' file, I would suggest to edit your default behaviour of your code.
i.e edit the *visual* and *visual_from_scratch* files by changing the default value of the *path-prefix* parameter from 'ckpt/pre' to 'ckpt/pre_full
